const String LoginMessage = 'login_message',
    SignUpGoogle= "sign_up_google",
    Slack= "slack",
    Office= "office",
    AllMeetings= "all_meetings",
    RecentNotes= "recent_notes",
    Dashboard= "dashboard",
    Notes= "notes",
    Action= "action",
    Settings= "settings",
    Logout= "logout",
    LogoName= "logo_name",
    ActionItems= "action_items",
    JustNow= "just_now",
    NoAssignee= "no_assignee",
    Attachment= "attachment",
    Success= "success",
    StartNotes= "start_notes",
    Team= "team",
    Unknown= "unknown",
    Upcoming= "upcoming",
    Today= "today",
    SearchApp= "search_app",
    ProfileInfo= "profile_info",
    Email= "email",
    NotificationPref= "notification_pref",
    SendViaEmail= "send_via_email",
    DailySummary= "daily_summary",
    SendViaSlack= "send_via_slack",
    Logo= "logo",
    Or= 'OR',
    SharedNotes= "share_notes";



final en= {
 LoginMessage: "Meetings that get things done",
 SignUpGoogle: "Sign up with google",
 Slack: "Slack",
 Office: "Office 365",
 AllMeetings: "All meetings",
 RecentNotes: "Recent Notes",
 Dashboard: "Dashboard",
 Notes: "Notes",
 Action: "Action",
 Settings: "Settings",
 Logout: "Logout",
 LogoName: "MEETNOTES",
 ActionItems: "ACTION ITEMS",
 JustNow: "just now",
 NoAssignee: "No Assignee",
 Attachment: "Attachment",
 Success: "Success",
 StartNotes: "Start taking Notes",
 Team: "team",
 Unknown: "Unknown",
 Upcoming: "Upcoming",
 Today: "Today",
 SearchApp: "Search App",
 ProfileInfo: "Profile Information",
 Email: "Email",
 NotificationPref: "Notification Preferences",
 SendViaEmail: "Daily Summary via Email",
 DailySummary: "DAILY_SUMMARY",
 SendViaSlack: "Daily Summary via Slack",
 Logo: "MeetNotes",
 Or: "OR",
 SharedNotes: "Share Notes",
};